load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
 
http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/7ee260c54921571b18b15049304426fe151c1265.zip"],
  strip_prefix = "googletest-7ee260c54921571b18b15049304426fe151c1265",
)
